version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - knowledge-base-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DB_PATH=/app/database/knowledge_base.db
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./backend:/app
      - ./database:/app/database
      - /app/node_modules
    networks:
      - knowledge-base-network

networks:
  knowledge-base-network:
    driver: bridge

volumes:
  database_data:
  uploads_data:
